version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  
  db:
    image: postgres:15.4-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=docker-tutorial-db
      - POSTGRES_USER=devkya
      - POSTGRES_PASSWORD=1q2w3e!Q
    ports:
      - "5432:5432"
    container_name: postgres_db
